import {
    FaAndroid,
    FaApple,
    FaGlobe,
    FaLinux,
    FaPlaystation,
    FaWindows,
    FaXbox,
} from "react-icons/fa6";
import { RxCross2 } from "react-icons/rx";
import { IconType } from "react-icons/lib";
import { MdPhoneIphone } from "react-icons/md";
import {
    SiNintendogamecube,
    SiPlaystationvita,
    SiNintendoswitch,
    SiNintendo3Ds,
    SiAtari,
    SiCommodore,
    SiNintendo,
    SiPanasonic,
    SiSega,
    SiWii,
    SiWiiu,
    SiNeovim,
} from "react-icons/si";
import { FrameIcon } from "@radix-ui/react-icons";

export const iconsMap: { [key: string]: IconType } = {
    pc: FaWindows,
    playstation5: FaPlaystation,
    playstation4: FaPlaystation,
    "xbox-one": FaXbox,
    "xbox-series-x": FaXbox,
    "nintendo-switch": SiNintendoswitch,
    ios: MdPhoneIphone,
    android: FaAndroid,
    "nintendo-3ds": SiNintendo3Ds,
    "nintendo-ds": SiNintendo3Ds,
    "nintendo-dsi": SiNintendo3Ds,
    macos: FaApple,
    linux: FaLinux,
    xbox360: FaXbox,
    "xbox-old": FaXbox,
    playstation3: FaPlaystation,
    playstation2: FaPlaystation,
    playstation1: FaPlaystation,
    "ps-vita": SiPlaystationvita,
    psp: FaPlaystation,
    "wii-u": SiWiiu,
    wii: SiWii,
    gamecube: SiNintendogamecube,
    "nintendo-64": SiNintendo,
    "game-boy-advance": RxCross2,
    "game-boy-color": RxCross2,
    "game-boy": RxCross2,
    snes: RxCross2,
    nes: SiNintendo,
    macintosh: FaApple,
    "apple-ii": FaApple,
    "commodore-amiga": SiCommodore,
    "atari-7800": SiAtari,
    "atari-5200": SiAtari,
    "atari-2600": SiAtari,
    "atari-flashback": SiAtari,
    "atari-8-bit": SiAtari,
    "atari-st": SiAtari,
    "atari-lynx": SiAtari,
    "atari-xegs": SiAtari,
    genesis: SiSega,
    "sega-saturn": SiSega,
    "sega-cd": SiSega,
    "sega-32x": SiSega,
    "sega-master-system": SiSega,
    dreamcast: SiSega,
    "3do": SiPanasonic,
    jaguar: SiAtari,
    "game-gear": SiSega,
    neogeo: SiNeovim,
};
