import NavBar from "@/components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import { Theme } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { BioRhyme as MainFont } from "next/font/google";
import "./globals.css";
import "./theme-config.css";

const mainFont = MainFont({ subsets: ["latin"], variable: "--font-main" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={mainFont.variable}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange
                >
                    <Theme
                        accentColor='crimson'
                        grayColor='sage'
                        radius='large'
                    >
                        {" "}
                        <NavBar />
                        <main>{children}</main>
                        {/* <ThemePanel/> */}
                    </Theme>
                </ThemeProvider>
            </body>
        </html>
    );
}
